### ISSUE TITLE
Not working on 5.6.1

### ISSUE THREAD

**Issue by SpencerElggren** [bendobos/LoupeXIVDeck#8]
It is not successfully installing when trying to install. My assumption is that this repository hasn't been updated for a year, and is out of date with the current loupedeck software. Is it still being maintained? Or would there be another reason that this is just failing to install?

**Comment by bendobos** [comment]
Hi @SpencerElggren,
you are right - this plugin is not maintained anymore.

I have updated the readme to reflect that.
